# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sendgrid"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Max Zhylinski"]
  s.date = "2012-02-24"
  s.description = "Sendgrid support for rails"
  s.email = "uzzable@gmail.com"
  s.files = [
    "Rakefile",
    "lib/sendgrid.rb",
    "lib/sendgrid/base.rb",
    "lib/sendgrid/railtie.rb",
    "lib/sendgrid/version.rb",
    "readme.textile",
    "sendgrid.gemspec"
  ]
  s.homepage = "https://github.com/uzzz/sendgrid"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Sendgrid support for rails"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

