# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sendgrid}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Max Gilinsky"]
  s.date = %q{2011-05-05}
  s.description = %q{Sendgrid support for rails}
  s.email = %q{uzzable@gmail.com}
  s.files = [
    "Rakefile",
    "lib/sendgrid.rb",
    "lib/sendgrid/base.rb",
    "lib/sendgrid/railtie.rb",
    "lib/sendgrid/version.rb"
  ]
  s.homepage = %q{https://github.com/uzzz/sendgrid}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Sendgrid support for rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

